<div class="not-found blog-content">
   <div class="container">
      <h1 class="h2-head">Not Found</h1>
      <div class="row">
         <div class="col-md-12 col-sm-12 aos-init aos-animate" data-aos="fade-up" data-aos-duration="1500">
               <div class="alert alert-warning">
                  Sorry, but the page you were trying to view does not exist. You can go back to <a href="/">Home</a> page here.
               </div>
         </div>
      </div>
   </div>
</div>