<div id="<?= $this->pluginId; ?>" class="news-list-plugin">
    <div id="news-list-plugin">   
        <div class="news">
        	<?php if (!empty($this->listNews->count())): ?>
               <?php foreach ($this->listNews as $val): ?>
                  <div class="loop-item col-lg-12">
                     <div class="item row blog-loop">
                        <div class="col-lg-6 col-md-6">
                           <div class="blog-img">
                              <?php if(!empty($val['cnews_image1'])): ?>
                              <a href="<?= $val['newsLink']; ?>">
                                 <img src="<?= $val['cnews_image1']; ?>" alt="...">
                              </a>
                              <?php endif; ?>
                           </div>
                        </div>
                        <div class="col-lg-6 col-md-6 blog-flex">
                           <div class="blog-text">
                              <a href="<?= $val['newsLink']; ?>" class="title">
                                 <h2><?= $val['cnews_title']; ?></h2>
                              </a>
                              <div class="blog-date">
                                 <span><img src="/Authors/assets/img/user.png" alt="user"> Rose Ethridge</span>
                                 <span><img src="/Authors/assets/img/date.png" alt="date"> November 1, 2018</span>
                              </div> 
               
                              <div class="blog-summary">
                                 <p><?= $val['cnews_paragraph1']; ?></p>
                              </div>
                              <a href="<?= $val['newsLink']; ?>" class="read-more">Read More</a>
                           </div>
                        </div>
                     </div>
                  </div>
              	<?php endforeach; ?>
          	<?php else: ?>
          		<div class="col-sm-12 col-md-12">
          			<div class="alert alert-warning" role="alert">
            			No result
            		</div>
          		</div>
          	<?php endif; ?>
        </div>
    </div>

    <!-- Pagination -->
    <?php
        // Generating Pagination Control using partial view
        echo $this->paginationControl(
                $this->listNews,
                'Sliding',
                'MelisCmsNews/list-paginator',
                array(
                    'searchKey' => $this->searchKey,
                    'dateMin' => $this->dateMin,
                    'dateMax' => $this->dateMax,
                    'nbPageBeforeAfter' => $this->nbPageBeforeAfter
                )
        );
    ?>
</div>