<div class="not-found blog-content">
   <div class="container">
      <h1 class="h2-head">404</h1>
      <div class="row">
         <div class="col-md-12 col-sm-12 aos-init aos-animate" data-aos="fade-up" data-aos-duration="1500">
               <div class="alert alert-warning">
                  This Page does not exist
               </div>
               <div class="home-btn">
               <a href="/" target="_blank" class="btn-style buy-book" rel="noopener">Proceed to Homepage</a>
               </div>
         </div>
      </div>
   </div>
</div>